apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 10m
  chart:
    spec:
      chart: rancher-latest
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: cattle-system
      version: 2.12.x
  valuesFrom:
    - kind: ConfigMap
      name: rancher-values