apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher-latest
  namespace: cattle-system
spec:
  interval: 1m
  url: https://releases.rancher.com/server-charts/stable