---
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: vscode
      namespace: default
      annotations: 
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`vscode.lab.markaplay.net`)
          kind: Rule
          services:
            - name: vscode-service
              port: 3000
      tls:
        secretName: vscode-tls