---
apiVersion: v1
kind: Service
metadata:
  name: vscode-service
  namespace: lab
spec:
  selector:
    app: vscode-server
  ports:
  - name: http
    protocol: TCP
    targetPort: 3000
    port: 3000
