apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ntfy-deployment.yaml # deployment definition
  - ntfy-svc.yaml # service connecting pods to cluster network
  - ntfy-pvc.yaml # pvc used to store cache and attachment
namespace: ntfy # select namespace for whole application 