apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy-deployment
  labels:
    app: ntfy-deployment
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: ntfy-pod
  template:
    metadata:
      labels:
        app: ntfy-pod
    spec:
      containers:
        - name: ntfy 
          image: binwiederhier/ntfy:v2.14.0
          args: ["serve"]
          env: 
            - name: TZ # set timezone
              value: America/Toronto
            - name: NTFY_DEBUG
              value: "false"
            - name: NTFY_LOG_LEVEL
              value: INFO
          ports: 
            - containerPort: 80
              name: http-ntfy
          resources:
            limits:
              memory: 300Mi
              cpu:  200m
            requests:
                  cpu: 150m
                  memory: 150Mi
          volumeMounts:
            - mountPath: /etc/ntfy
              name: config 
              readOnly: true
            - mountPath: /etc/ntfy/templates
              name: template-volume
              readOnly: true
            - mountPath: /var/cache/ntfy
              name: cache-volume
            - mountPath: /var/lib/ntfy
              name: auth-volume
      volumes:
        - name: config
          configMap:
            name: ntfy-server-config
        - name: template-volume
          configMap:
            name: template-config
        - name: cache-volume
          persistentVolumeClaim:
            claimName: ntfy-pvc
        - name: auth-volume
          persistentVolumeClaim:
            claimName: ntfy-auth-pvc