---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-tls
  namespace: cattle-system
spec:
  secretName: rancher-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "armrancher.lab.markaplay.net"
  dnsNames:
  - "armrancher.lab.markaplay.net"
