apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: internal-pool
    namespace: metallb-system
spec:
    addresses:
        - 10.0.0.40-10.0.0.50
        - 10.0.0.100/32
        - 10.0.0.114/32
