apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsshcode-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vsshcode-server
  template:
    metadata:
      labels:
        app: vsshcode-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: markaplay.jfrog.io/custom-images/vscode-server:ubuntu-1.1.6
        name: vscode-server-ssh
        command:
          - ""
        tty: true
        volumeMounts:
          - name: vsshcode-vol
            mountPath: /data
        ports:
        - containerPort: 22
        resources:
          requests:
            cpu: 400m
            memory: 1024Mi
          limits:
            memory: 1024Mi
      imagePullSecrets:
        - name: jfrog-credential
      volumes:
        - name: vsshcode-vol
          persistentVolumeClaim:
            claimName: vsshcode-volv-pvc