apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      version: 2.5.1
  values:
    loki:
    persistence:
        enabled: 'true'
        storageClassName: 'rook-cephfs'
        size: '10Gi'