apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: moniotring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      version: 20.3.0
  values:
    loki:
    persistence:
        enabled: 'true'
        storageClassName: 'nfs-client'
        size: '5Gi'