---
apiVersion: v1
kind: Namespace
metadata:
  name: git
  labels:
    app: gitness
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitness-volv-pvc
  namespace: git
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitness
  namespace: git
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gitness
  template:
    metadata:
      labels:
        app: gitness
    spec:
      containers:
      - image: harness/gitness:latest
        name: gitness
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            name: http
        volumeMounts:
          - name: data-volume
            mountPath: /data
        env:
          - name: GITNESS_URL_BASE
            value: "https://git.lab.markaplay.net"
        resources:
            limits:
              memory: 1.5Gi
            requests:
              memory: 1Gi
              cpu: "1"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: gitness-volv-pvc