---
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: searxng
      namespace: searxng
      annotations: 
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`search.cloud.markaplay.net`)
          kind: Rule
          services:
            - name: searxng
              port: 8080
      tls:
        secretName: searxng-tls