apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 1m
  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
      version: 1.0.0
  values:
    replicas: 3
    env:
      INSTANCE_NAME: "MAP-LKE-searxng"
      BASE_URL: "https://search.cloud.markaplay.net"
      AUTOCOMPLETE: "true"
      TZ: "America/New_York"
    redis:
      enabled: true