apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
type: Opaque
data:
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:GlpL6MRmIoMB1yJkL0L0g7Q=,iv:oB3ztgXlD19vYShdoe4ypfA9gUf3qJnXegbsLOr7Wig=,tag:tjR0U+XRh6fFfLhIXpcqqQ==,type:str]
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:3sKXMMYXsMdd7S4vHA==,iv:ulDy4mtzn+AMiNEFD9/+biVfGSboylu7TjC2q7nfR7U=,tag:VwQtFbnZA09bx3QlYgxXmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZjNBb0Y4djdaWVo4cWln
            MFdxSWJIcTFwMUI4bmtnMTh2MXRreVkrV1RZCktzT1AxSVlscGFBdmV2cko5aHVG
            UjN1ekVIZHhLcHd4dU1NbDBjY1hlS1kKLS0tIDRUM3dzaEpJM2ZPdElDeVQ2cW9p
            ZjRFOHpyWFBlQ0xodDU3YW5KKzZuY28KLppE3x3TMuN38Po0QuAQEwA81sxG68ih
            jwLxy8S/iNTRf9VQ6CDZ0Bp3evI/62l0N3lb3/B7FtDUYyyP47dQjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T00:01:00Z"
    mac: ENC[AES256_GCM,data:bK8QnNY8Vxl+q0xTx78/XVJpBLViuyEiCHN5IJJpDbQdvul3WFWvuo01tCKS0qE7a0BhhMbUgFfZJ2KfxC0WmF/mnbSTnRmbV3Zwh0qDOozbLxy0yeDdE7G41e7974XN8mlBay/MmdWXmI2tMy4ZJ8ev9F5OWBBa5Nxka9kb9nM=,iv:lZnMZ6mHE8Y/jBHCgfGKV8Aykhf91xnNNzZvy2Jqfz4=,tag:N4PV/G5TYrU2Gj+HFtx1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
