apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: '20.3.0'
      interval: 1m
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          
    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: internal-pool
      labels: {}
      spec:
        loadBalancerIP: 10.0.0.45 # this should be an IP in the MetalLB range
      loadBalancerSourceRanges: []
      externalIPs: []