---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bots
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discord-bots
  template:
    metadata:
      labels:
        app: discord-bots
    spec:
      containers:
      - image: ghcr.io/markaplay-game-hosting/mapbot:dev
        name: discord-dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: discord-secrets
        resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
              cpu: 1