apiVersion: v1
kind: Secret
metadata:
  name: discord-secrets
type: Opaque
data:
  TOKEN: 'OTkwNjgxNjkyOTMzMDk1NDc1.GIr_ZY.1ve5I1MjzSDqOhnVcVYgpG6yt6VRF6KIL4mJK4'
  Prefix: '~'
  SecretToken: 'YmJiYWU5ODQtNDFlOC00ZWVmLWI5NmMtZTFlMjU4ZGM2ZDlkOjR5dTk3VUVNblhtSDZHY2tLNHRmOW1sVGtldDRIS3ZBYzdubzhqQUZXM0ZqY3BDem1MT2RSbXRmVE5xbTNDaHU='
  DOUrl: "https://faas-tor1-70ca848e.doserverless.co/api/v1/namespaces/fn-27fd00a7-f72b-41e8-96b5-a475688fb6ca/actions/Amp-Status?blocking=true&result=true"
  DATABASEHOST: "mysql"
  DATABASEPORT: "3306"
  DATABASEUSER: "root"
  DATABASEPASSWORD: "root"