apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: errors-and-warnings
  namespace: flux-system
spec:
  summary: "cluster addons"
  eventMetadata:
    cluster: "nasa"
  providerRef:
    name: ntfy
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'