apiVersion: v1
kind: Secret
metadata:
    name: bearer-auth
    namespace: flux-system
type: Opaque
stringData:
    headers: ENC[AES256_GCM,data:QGCyXTzjhJYM6VpPtytbdlG4r5Zb3b6RMvonsPFY/x3k20VMTzZ3J53Gv9h6o416UE1ExkffUg==,iv:9uK7wSNGQwtHsBux6BAR1g3wjmer9mtIsiBsPoMDDDU=,tag:9chWwGRf+IVzVv23YlJt3w==,type:str]
sops:
    age:
        - recipient: age1z009ewmj2adfms328f3mc6aux27qq4d2mwhyunat9ul5x9k3fydq8mzxhr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMklNY2VOQjhEcGpOSU5Z
            ZXpuTTNTb1RKSWdqWWtodW84NEFvL0tXUmhRCnl2UUZyenRZb1JScUJxb1gvVTdD
            VlZDSVY4N2xjNnVoYzFjbDhObDFORVUKLS0tIDR6UWVPSzQ5dm1MaVBlVEoxYTNO
            cXlhT2ttbXRiWjRESVlLak1TVEYzdWsKTVOLQ6gdFnRJzGzopLbXKMeJ9JB1yviw
            DJSlmcsipIU3/w9RcC9dWYaad/lA1JFOFw8ZSGaOr09qwC8NugmaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T02:12:43Z"
    mac: ENC[AES256_GCM,data:FSaW3U1qPEmrNV5Qf5mZmE/0Apn5FVKPhD+NfwYaaYcIvVY3JCdbCeJMDziY1kx8hRXYbeigtPaPQOlFLEI+Dkfo4aOBWhzVnzwMU5yLgTa9s6sjSHuw2NWY1dzzgljJlhxAYOtmaGrJdEQN7lU0m6Un9yj/mFqkFdTjm+NZ1XA=,iv:Ss4W9t62qW9nQc/OtWrcf+L4FEdspptBYV5/6uBlpGo=,tag:+6+pb27Y1pAk2TV2JKm/yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
