apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone
    namespace: drone
spec:
    interval: 1m
    chart:
        spec:
            chart: drone
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: flux-system
            version: 0.6.4
    values:
        env:
            DRONE_SERVER_HOST: ENC[AES256_GCM,data:eW4C1erpQa+5WBf3OfDrJPOOTJBrMMYfdqcWoQ==,iv:MZuTgfiQwSjzkOAaPz5iv8N//azp2y7HyzXZFatwRAU=,tag:PhkXlFSg7LqT51KbPvmi5w==,type:str]
            DRONE_SERVER_PROTO: ENC[AES256_GCM,data:JWqyOf8=,iv:Ww2c/tEehWW0oROd9sGXl4yxPeSTMgaXYWtOBM9yxhI=,tag:7iEGeOvtwX4AhW8F5tLTyQ==,type:str]
            DRONE_RPC_SECRET: ENC[AES256_GCM,data:SoipopNx3T8cBB9DU1hJnwEW5eZsqK9vTzoII4kCs04=,iv:auOuJQY6ThNPsBQT4jY+mvIidKi4MVcKkPPSHL0IRi8=,tag:FSbXYAfBiCK4ENmdvZEoZQ==,type:str]
            DRONE_GITEA_CLIENT_ID: ENC[AES256_GCM,data:2xju37UCPeSitZvhisDFNnBsMfvpkm/fNoXyXqpsIyw=,iv:c7mlOom5PY7FyNCCRN4CEymhMXEgN/B2jcbAcp1+21A=,tag:fbXzfkLk6ItkxVFLRrLjRw==,type:str]
            DRONE_GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:EuaNqahEyJNVky5plU/ek3XD1L6Fsa6fgNbMoCLAW1nir7BAW7Av+WT3EmoY553nO7PahA8Io/s=,iv:q82/mX8hmDXTVQP2objACyqprDelF4YeiKd1+dQ+djo=,tag:OtRVbiyyV44zpAdiUQF9qg==,type:str]
            DRONE_GITEA_SERVER: ENC[AES256_GCM,data:xHqaNS9X1UknvWpGWaj15ggN/SdIdAEvBh7bvhE=,iv:2txJqK54sO2eti7q+cza5vxv0U70kVJG8Jj5KQypWSs=,tag:veSOeqAy429H5SKDp3mhsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WXF0eDB0cCtkd2Q3a1hQ
            SnhLWFdwTXVKaHM1RDdyUG5MZVQwZDd6MzNvCjFGK2NMVkdvMFJseHcvVGZXLzlH
            SnNnbTdDUVpwU3RoaDdacVhVSTVDdEkKLS0tIEFUMzJ3Mk0yWnV4MlEzbGRpTmZZ
            dUNTdUwyTU9Mc0Z3cFhyK1pDUHBHelUKJfsbGV9mHUYJigkjW/6wAlCSeLpqUGFs
            Q60WiNMjsKyR5H+PICUluC5WRxTFur6hi7sMNYwmLuPGB/UJ6YUYqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T01:20:14Z"
    mac: ENC[AES256_GCM,data:P790YHbGfL8ril40BLZQwIIThCWvXp7mN7bHEXpbNsGh+GgbxmCsz5GOfVag9dKrIUVbhdtMaYvYV1L5Sikq2JJyatzgokSSOT9ztPRy96+jun6pBgGDxyFt0V0KHDwQMVgLaAjdsEVFNoT8fSdVk1SSX6R1Fo2JajAzFpYWIWM=,iv:4jZhOMyb1lTTmVhRavTfylH8ZyhQPo6ZOYSYbIpws4U=,tag:rkMQVPEsdfLOjm+YKS27sQ==,type:str]
    pgp: []
    encrypted_regex: ^(env)$
    version: 3.7.3
