apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone
    namespace: droneci
spec:
    interval: 1m
    chart:
        spec:
            chart: drone
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: flux-system
            version: 0.6.5
    values:
        env:
            DRONE_SERVER_HOST: ENC[AES256_GCM,data:uAWeyIuQIUzF46H2BaWeHe02gJY=,iv:KhP+za7+FWuZCsW2Wl2jyxC6UMYMwFPlYi9DCzSKc04=,tag:qDKPJuDq5Ef+FLGqRyCfng==,type:str]
            DRONE_SERVER_PROTO: ENC[AES256_GCM,data:nqK7Hw==,iv:tEAYfNTqyK4HaxnCLFTu5Lyr7M5MPuOxNM5BqeqByGs=,tag:vw4RoV4JQBb6YBkjX1BCHg==,type:str]
            DRONE_RPC_SECRET: ENC[AES256_GCM,data:qaf4vycKWlgNGmW1mKiS9MxxoBCBNrOVZoh9,iv:eNdMTZ5+++A+uudhSwvlek+fshWVmLdo2bKXxAFFMvM=,tag:S/9oJB+KcIbn1SeNxQcfxg==,type:str]
            DRONE_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:9vlymw1+l51TGeLX3fy0QQGUa/Q=,iv:j4vCsnsHMLLeRr6TZQPV9zOXqr2LnvfcpQkuuDxrK8M=,tag:uEfdst7ESYln/xiw9in1uQ==,type:str]
            DRONE_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:OmxPVnUwrPVvlpS6bWI2OJKgT/+NxoeHVUycdQsl6zrtcTeO/kaNeA==,iv:qXRoslR3abNwvhLxaEE46zk/07iB1uf9HGhSbDJ64eM=,tag:YQsdicAIt9jrsl/kyWLi7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV3BTbis2SFRaTzM4TE9Z
            N25sekwxZUFxdWxtVVFhQVBoUW9Oc2p6S0VnCjBUZU9GLzg5TFpiYWs2UUh3Q25l
            MlNCYlF6WFR0NGcwWG9ySjlqejc2YnMKLS0tIEZ6QnBDSElTbmFRZHpKZVd3OE1N
            N0lXM25MdHYyZnFuT1JSRmZsM1cxNTgKltu7MRL7RIKdLfYfrdmRLPEHOMd27kpP
            oIk18+Nz3Wpkd5D74ojg2ma9G0a2Tv/oXZjOnki5fuhoWgdm10ux6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T00:27:46Z"
    mac: ENC[AES256_GCM,data:/XuB2nW/y6PErSOkY6FJYXua/LNYIVjyaH50QJ7AZFfbtjyN9xiXMGHfxltLtz1jgXRx4Ukuor8jf9gjg/pduSM30358sUkmjCbKpRr4EBKTm0I6QdTervLtyWf71aI+aixxO/d5S9S3EbMkmvcE6K1Q0ARqKlV/woLqm40zsNU=,iv:mQgJbVVHJokeQfyOl5svTNjne8zBcYe73cd0u1izZAE=,tag:0pe67g3HzvpF3nxgOGuE3w==,type:str]
    pgp: []
    encrypted_regex: ^(env)$
    version: 3.8.1
