apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../../../workloads/ntfy
  - ntfy-ingress.yaml
  - ntfy-certificate.yaml
namespace: ntfy

configMapGenerator:
    - name: server-config
      files: 
        - server.yaml
#    - name: template1-config
#      files:
#        - ./templates/flux-alerts.yaml