apiVersion: v1
kind: ConfigMap
metadata:
    name: ntfy-server-config
    namespace: ntfy
data:
    server.yml: |-
        base-url: https://ntfy.ovh.markaplay.net
        cache-file: /var/cache/ntfy/cache.db
        attachment-cache-dir: /var/cache/ntfy/attachments
        auth-file: "/var/lib/ntfy/user.db"
        auth-default-access: deny-all
        behind-proxy: true
        enable-login: true
        enable-metrics: true
