apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - image: freshrss/freshrss:latest
        name: freshrss
        volumeMounts:
          - name: freshrss-data
            mountPath: /var/www/FreshRSS/data
          - name: freshrss-extensions
            mountPath: /var/www/FreshRSS/extensions
        env:
          - name: CRON_MIN
            value: 1,31
          - name: TZ
            value: America/Toronto
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1
            memory: 500Mi
          limits:
            cpu: 1
            memory: 500Mi
      initContainers:
      - image: alpine:latest
        name: init-extensions
        command: [ "/bin/sh","-c" ]
        args: [ "apk --update wget unzip; wget https://github.com/DevonHess/FreshRSS-Extensions/archive/refs/heads/main.zip -O rss-bridge.zip; unzip rss-bridge.zip -d /extensions; rm rss-bridge.zip " ]
        volumes:
        - name: freshrss-extensions
          mountPath: /extensions
        resources:
          requests:
            cpu: 1
            memory: 500Mi
          limits:
            cpu: 1
            memory: 500Mi
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data-pvc
        - name: freshrss-extensions
          persistentVolumeClaim:
            claimName: freshrss-extensions-pvc