apiVersion: v1
kind: ConfigMap
metadata:
  name: pterodactyl-config
  namespace: pterodactyl
data:
  DB_DATABASE: "pterodactyl_panel"
  APP_ENV: "production"
  APP_ENVIRONMENT_ONLY: "false"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_DRIVER: "redis"
  REDIS_HOST: "caching"
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  TRUSTED_PROXIES: "*"
  APP_TIMEZONE: "America/Toronto"
  APP_URL: "https://panel.lab.markaplay.net"
  APP_BACKUP_DRIVER: "s3"