kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-panel-app-claim
  namespace: pterodactyl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-panel-nginx-claim
  namespace: pterodactyl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-panel-logs-claim
  namespace: pterodactyl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-db-claim
  namespace: pterodactyl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi