apiVersion: batch/v1
kind: CronJob
metadata:
  name: proxbackupstatus
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: proxbackup
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - 
          restartPolicy: OnFailure