---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: monitoring
spec:
  secretName: prometheus-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "metrics.huston.lab.markaplay.net"
  dnsNames:
  - "metrics.huston.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`metrics.huston.lab.markaplay.net`)
      kind: Rule
      services:
      - name: kube-prometheus-stack-prometheus
        port: 9090
  tls:
    secretName: prometheus-cert
