apiVersion: v1
kind: Service
metadata:
  name: teamspeak
  labels:
    app: teamspeak
spec:
  type: LoadBalancer
  ports:
  - port: 9987
    targetPort: 9987
    protocol: UDP
    name: voice
  - port: 30033
    targetPort: 30033
    protocol: TCP
    name: filetransfer
  - port: 10011
    targetPort: 10011
    protocol: TCP
    name: query
  selector:
    app: teamspeak
  loadBalancerIP: 51.222.45.215