apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: postgres
    namespace: postgres
spec:
    interval: 1m
    chart:
        spec:
            chart: postgresql
            sourceRef:
                kind: HelmRepository
                name: postgresql
                namespace: flux-system
            version: 12.7.3
    values:
        global:
            storageClass: longhorn
            postgresql:
                auth:
                    existingSecret: postgresql-db-secrets
                    secretKeys:
                        usernameKey: username
                        passwordKey: password
                        replicationPasswordKey: replicationPassword
                    database: semaphore
        tls:
            enabled: true
            certificateSecret: postgres-tls
        service:
            type: LoadBalancer
            loadBalancerIP: 10.0.0.42
