apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:uOY75FnLphagNXtCx4QY+t0p4n1Ugn4nA0X7ukEGi3+o8N79cjUDeQ==,iv:vQ0SSfDpa5WizD9dMDGGt43xmJagnDwjhnT4/h2mNkA=,tag:CKZms/v8Fe90CFwInm3/ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ayt4OEVsczBPZERrZ2ts
            K2RteWVaUlBVYm9ITHdXMTdHdFBwUXFBbERvCkhCR3Vadm9aN0VvNW1Hb0N5WUM1
            cVZHRlF4NWRUQWJqU0NKcURHdW5LOU0KLS0tIDQ5RFZOdDh4RXZQdjREd01BT1Bt
            NEhFYnF4QjN1czU5TVVCeVI4Smw0Y2cKHrJqOrL3zJfqcnEXVQIYC6EKnL97nYvk
            S6ivno0hG16gRpSToafuJypqJdiLYR+qeg4xO+4rfOEZeu02O8nzRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T19:29:00Z"
    mac: ENC[AES256_GCM,data:PXsouc1Iwg6eXLbG3Wpv5r4Sts4ddqcw/4LXmpSUgugDp5EGOUAXmEIdW/AWUm3BuwXS60TFHFcnkimUiEQZi3pL4CAUPugvaU8M33MLe/QM/aZAcH7KipcdiCAfUtKn0BZUrlsOpkaVpR0rnn7UmBaWi1VbWV+HvYu3iUasMhU=,iv:h1sdIvvyuYombqf/N+t8CmVnm0v1hMzW9rM2/3S8ym4=,tag:Yl59xSlO9+Pt6dLtkdv4LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
