apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:kcnOEBuQaj+2CEyDl3c1o3A6OwVJIH+ZTQT9ie07IK5+TnDG8ZTOow==,iv:YY5URbZdpE1h9Vg7dH78KzJb6XEGlEvE4GitdjZXgCU=,tag:hmNVydr8Zv1E73MMGycZIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ayt4OEVsczBPZERrZ2ts
            K2RteWVaUlBVYm9ITHdXMTdHdFBwUXFBbERvCkhCR3Vadm9aN0VvNW1Hb0N5WUM1
            cVZHRlF4NWRUQWJqU0NKcURHdW5LOU0KLS0tIDQ5RFZOdDh4RXZQdjREd01BT1Bt
            NEhFYnF4QjN1czU5TVVCeVI4Smw0Y2cKHrJqOrL3zJfqcnEXVQIYC6EKnL97nYvk
            S6ivno0hG16gRpSToafuJypqJdiLYR+qeg4xO+4rfOEZeu02O8nzRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T00:18:36Z"
    mac: ENC[AES256_GCM,data:Qi3mxDwTKP4wHslCoZyECIeKYnVytsQ0q780CfbljKnBh0a/8I7Z0atIHZx+lcs/y/khr6hS9ItqDolsxudSUQFe5HMeWZWErOClrdZ9C80768iv2jC7u700//4l6iEOHI9ScmRCwccM/RHlKbbRQMWvegBA33BX8t18o72f2XY=,iv:EhIQIUKzFIolAmpssDr633a4iv0zSefNpxqATXtJtYU=,tag:WS3SQ5ysLqZTbHC+0SzB+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
