---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bitwarden.cloud.markaplay.net"
  dnsNames:
  - "bitwarden.cloud.markaplay.net"