---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dns
  namespace: dns
spec:
  secretName: dns-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "dns.lab.markaplay.net"
  dnsNames:
  - "dns.lab.markaplay.net"