---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bots
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discord-bots
  template:
    metadata:
      labels:
        app: discord-bots
    spec:
      containers:
      - image: ghcr.io/markaplay-game-hosting/mapbot:dev
        name: discord-dev
        imagePullPolicy: Always
        envfrom:
        - secretRef:
            name: discord-secrets
        resources:
            limits:
              memory: 2Gi
              cpu: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.30
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 'root'
        volumeMounts:
          - name: mysql-volv
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        resources:
            limits:
              memory: 4Gi
              cpu: "2"
      volumes:
        - name: mysql-volv
          persistentVolumeClaim:
            claimName: mysql-volv-pvc