apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid-deployment
  labels:
    app: pocketid
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      containers:
        - name: pocketid 
          image: ghcr.io/pocket-id/pocket-id:v1
          ports: 
            - containerPort: 1411
              name: http-pocketid
          resources:
            limits:
              memory: 300Mi
              cpu:  200m
            requests:
                  cpu: 150m
                  memory: 150Mi
          volumeMounts:
            - mountPath: /app/data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pocketid-pvc