---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-pvc
  namespace: pocketid
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi