---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "longhorn.lab.markaplay.net"
  dnsNames:
  - "longhorn.lab.markaplay.net"
