apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cattle-system
resources:
  - ../../../../infra/rancher
  - ingress.yaml
  - certificate.yaml

configMapGenerator:
  - name: rancher-values
    behavior: create
    namespace: cattle-system
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: false

# Let kustomize rewrite the name hash inside HelmRelease.spec.valuesFrom
configurations:
  - kustomizeconfig.yaml
