apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: traefik-values
    behavior: create
    files:
      - values.yaml=values.yaml

# Let kustomize rewrite the name hash inside HelmRelease.spec.valuesFrom
configurations:
  - kustomizeconfig.yaml
