apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 20.3.x
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
    deployment:
      enabled: true
      replicas: 3
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true

    ping:
      enabled: true

    dashboard:
      enabled: true

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false
    rbac:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 51.222.28.107
