apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 20.3.x
  values:
    deployment:
      enabled: true
      replicas: 3
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true


    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`nasa.markaplay.net`) && (PathPrefix(`/traefik/dashboard`) || Path(`/traefik/api`))
        entryPoints:
          - websecure
        middlewares:
          - name: traefik-dashboard-basicauth
            namespace: traefik
          - name: strip-traefik-prefix
            namespace: traefik
      ping:
        enabled: true
        matchRule: Host(`nasa.markaplay.net`) && (PathPrefix(`/traefik/ping`) || Path(`/traefik/ping`))
        entryPoints:
          - websecure

    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
        websecure:
          namespacePolicy:
            from: All
    rbac:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 51.222.28.107
