deployment:
  enabled: true
  replicas: 3
ports:
  web:
    redirectTo: websecure
  websecure:
    proxyProtocol:
      trustedIPs: ["10.8.0.2/32","10.0.50.250/32"]
    tls:
      enabled: true
providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
    websecure:
      namespacePolicy:
        from: All
rbac:
  enabled: true