---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bots
  namespace: discord
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discord-bots
  template:
    metadata:
      labels:
        app: discord-bots
    spec:
      containers:
      - image: vincdelta/discordbot:dev
        name: discord-dev
        imagePullPolicy: Always
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-secrets
              key: BOT_TOKEN
        - name: BOT_PREFIX
          valueFrom:
            secretKeyRef:
              name: discord-secrets
              key: BOT_PREFIX
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: discord-secrets
              key: API_URL
        resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi
              cpu: 1