---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bots
  namespace: discord
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: discord-bots
  template:
    metadata:
      labels:
        app: discord-bots
    spec:
      containers:
      - image: vincdelta/mapbot:dev
        name: discord-dev
        imagePullPolicy: Always
        envfrom:
        - secretRef:
            name: discord-secrets
        resources:
            limits:
              memory: 500MiB
            requests:
              memory: 500MiB
              cpu: 1