apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord
type: StringData
data:
    BOT_TOKEN: ENC[AES256_GCM,data:MRjj4D4IeZTbYTF4Pg0UbvoyGwX9UQcDJAP1MvtYXBvoL8h2PLC0iUK6WZfkkkPtziGhSqsvta1a91WsbCP9sxkvMWO+/w==,iv:HS3LqIPyqY3cyFjeuVa0+4YG99eOWko4ijZ5+pyB2iw=,tag:d7c5hlHLZRQfF2GbGB1PBQ==,type:str]
    BOT_PREFIX: ENC[AES256_GCM,data:9Q==,iv:DvkDfl7LRTv5MfXACHvlNqk7xOYPx627JhUjpQX3Jag=,tag:KiuebDRwqDC0FFYDWS0f1Q==,type:str]
    API_URL: ENC[AES256_GCM,data:rAYFuxeQ6lOee+6NIgPk3p5GVtWNH9ruQZi2KTsY33nuMqlMbKUzBYK/IPpuTQyKD2tlZyzu3vDVZLaE0U6znNv5inKGBtDO8Sflb87ucxS+GHTkYPeTVDPf8R0GLfKGDlSGsU1zIyK/Ln0=,iv:tPpSXiONWwkjXp7qaaSM+cNGROzPk0RO6NKGu9MmBhU=,tag:5L4xa03tUbYZ+4FfUsZ6Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYLytuU2JObkRlYklpWXMz
            enR1S1hJSm5sSWlrNWhBZ3JGQXlsNWs5bFF3CnQ4SnV4b20zL1QvOUZoT3hzeWdJ
            SHpsdVZSWHVlb1dlWk9jSzhSVFV3cDgKLS0tIGxEMWV1WitrOWkrZ0F0eFdveWZI
            TFowWGNaUUZHNWQxTFRvRnFFYkVTbTgKjOEL47QIzgd5IksD66OPVOVe7uT7sfVh
            QdKgyqkibQoP0/Znv8NKApe/mMwlxTGRq4uAa9gzkgZ7/yVl8N3jeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T22:16:14Z"
    mac: ENC[AES256_GCM,data:ndKOXlRgPfvzrbb9X/7PkHMrpPPLde4ubdDWLAhVB0+e+yycE5I5I+gJ5Lp2jZJau4LDBEUuh/PUhPgBCiTsK9RvxjiVjBDz3elLFV9/C2WgAoanzNI7PttVhorZvDQsCF/J39DSjwFjMGCzCk9UMJqc3emdhrc1zKubphoGoKs=,iv:uDJaRwu76N6Kkoa1fp0Fe+RBkSX17CByFPrAdu6K+CI=,tag:sjYA1esb1AK4PXHvrHwVzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
