---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
  namespace: postgres
spec:
  secretName: postgres-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "postgresdb.lab.markaplay.net"
  dnsNames:
  - "postgresdb.lab.markaplay.net"