---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openfaas-cert
  namespace: openfaas-fn
spec:
  secretName: openfaas-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "openfaas.lab.markaplay.net"
  dnsNames:
  - "openfaas.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-web
  namespace: openfaas-fn
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfaas.lab.markaplay.net`)
      kind: Rule
      services:
      - name: gateway
        port: 8080
  tls:
    secretName: openfaas-cert