apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: isito
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: isito
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: flux-system
      version: 
  values: