apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 20.3.0
  values:
    podAnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "kube-traefik-sa"
      vault.hashicorp.com/agent-inject-secret-traefik-credential.txt: "secret/data/kube-secrets/traefik"
      vault.hashicorp.com/agent-inject-template-traefik-credential.txt: |
        {{- with secret "secret/data/kube-secrets/traefik" -}}
        {{ .Data.data.user }}
        {{- end -}}
    serviceAccount:
      create: true
      name: traefik-service
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true

    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: 10.0.50.50 # this should be an IP in the MetalLB range
      loadBalancerSourceRanges: []
      externalIPs: []