---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng
  namespace: searxng
spec:
  secretName: searxng-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "search.cloud.markaplay.net"
  dnsNames:
  - "search.cloud.markaplay.net"