apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - searxng-deployment.yaml # deployment definition
  - searxng-svc.yaml # service connecting pods to cluster network
  - searxng-pvc.yaml # pvc used to store cache and attachment
  - config.yaml
namespace: searxng # select namespace for whole application 
