apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../../../base/traefik

configMapGenerator:
  - name: traefik-values
    behavior: merge
    namespace: traefik
    files:
      - values.yaml=values-huston.yaml

# Let kustomize rewrite the name hash inside HelmRelease.spec.valuesFrom
configurations:
  - kustomizeconfig.yaml
