
deployment:
  enabled: true
  replicas: 3
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true


ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.lab.markaplay.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints:
      - websecure
    middlewares:
      - name: traefik-dashboard-basicauth
        namespace: traefik

providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
    websecure:
      namespacePolicy:
        from: All
rbac:
  enabled: true
service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.0.50.10
