ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.lab.markaplay.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints:
      - websecure
    middlewares:
      - name: traefik-dashboard-basicauth
        namespace: traefik

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.0.50.10
