---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuma
  namespace: uptime
spec:
  secretName: kuma-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "uptime.lab.markaplay.net"
  dnsNames:
  - "uptime.lab.markaplay.net"
  - "uptime.lab.markaplay.net"