---
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: uptime
      namespace: uptime
      annotations: 
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`uptime.lab.markaplay.net`)
          kind: Rule
          services:
            - name: uptime-kuma
              port: 3001
      tls:
        secretName: kuma-tls