apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-volv-pvc
  storageClassName: "rock-cephfs"
  namespace: uptime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi