apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-volv-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  replicas: 6
  resources:
    requests:
      storage: 15Gi