---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elkstack-tls
  namespace: elkstack
spec:
  secretName: elkstack-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "elk.lab.markaplay.net"
  dnsNames:
  - "elk.lab.markaplay.net"