---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: 1.4.0
    values:
      persistence:
        enabled: true
        # Set to false to disable the `fsgroup-volume` initContainer that will update permissions on the persistent disk.
        enableInitChown: true
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 15Gi
        annotations: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-dashboard
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: opensearch-dashboard
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: 1.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: logstash
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: 8.5.1