---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-master
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: 2.6.0
  values:
    clusterName: "opensearch-cluster"

    nodeGroup: "master"

    masterService: "opensearch-cluster-master"

    roles:
      master: "true"
      ingest: "false"
      data: "false"
      remote_cluster_client: "false"

    replicas: 3

    # Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 2G
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-data
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: 2.6.0
  values:
    clusterName: "opensearch-cluster"

    nodeGroup: "data"

    masterService: "opensearch-cluster-master"

    roles:
      master: "false"
      ingest: "true"
      data: "true"
      remote_cluster_client: "false"

    replicas: 1

    # Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 20G
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-client
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: 2.6.0
  values:
    clusterName: "opensearch-cluster"

    nodeGroup: "client"

    masterService: "opensearch-cluster-master"

    roles:
      master: "false"
      ingest: "false"
      data: "false"
      remote_cluster_client: "false"

    replicas: 1

    # Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1G
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-dashboard
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: opensearch-dashboard
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: 2.6.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: elkstack
spec:
  interval: 1m
  chart:
    spec:
      chart: logstash
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: 8.5.1