---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: opensearch
  namespace: flux-system
spec:
  interval: 1m
  url: https://opensearch-project.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.elastic.co