apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: loki-stack
        namespace: flux-system
      version: 2.8.7
  values:
    grafana:
      enabled: 'true'
    prometheus:
      enabled: 'true'
      alertmanager:
        persistentVolume:
          enabled: 'false'
      server:
        persistentVolume:
          enabled: 'false'
    loki:
      persistence:
          enabled: 'true'
          storageClassName: 'rook-cephfs'
          size: '5Gi'
      rbac:
        pspEnabled: true