---
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: file-browser
      annotations: 
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`archive.lab.markaplay.net`)
          kind: Rule
          services:
            - name: file-browser
              port: 80
      tls:
        secretName: local-example-com-tls