apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: firefly
    namespace: firefly
spec:
    interval: 1m
    chart:
        spec:
            chart: firefly-iii-stack
            sourceRef:
                kind: HelmRepository
                name: firefly-iii
                namespace: flux-system
            version: 0.7.2
    values:
        firefly-db:
            # if you set this to false it will not be installed
            enabled: true
            image:
                repository: postgres
                tag: 10-alpine
                pullPolicy: IfNotPresent
            storage:
                class: longhorn
                accessModes: ReadWriteMany
                dataSize: 1Gi
            # environment variables
            configs:
                RESTORE_URL: ""
                BACKUP_URL: ""
                PGPASSWORD: ENC[AES256_GCM,data:kjDKh7D8j8F4ZOwPzViLieMcJ6zDGhNa+g==,iv:G1oJ9zgDy3rqNyT7OB28MHQdCG8NQZbgPbiU7N8Fc8k=,tag:eriOv8qjbCBsj1CBfHqTMw==,type:str]
                DBHOST: ENC[AES256_GCM,data:kzBd8/mlvTA8AJFCi0x78RIP,iv:4oZz2w+fvO4vsq6uyehBbxWC+YA92w3OVQUEPwTsP1Q=,tag:+thLx6lCvlj9klR9TLHqJQ==,type:str]
                DBPORT: ENC[AES256_GCM,data:3Be/hA==,iv:Hn1BTSTrqg+7V/4ad8ld1TDeEC7WbYxjiR4TfXDwuQU=,tag:+7NF6zafNaXPYFc0d3ofuA==,type:str]
                DBNAME: ENC[AES256_GCM,data:IfWxYmwb5g==,iv:hGyfNP6+u9I9+DDvDB5v27rjGOntPDYYHZvde4XJFUE=,tag:HexDwA614RdIcy+KLbvGFA==,type:str]
                DBUSER: ENC[AES256_GCM,data:hq2n64J56Q==,iv:0iJYNVKNu4iXIPc8NQCc1nryk3cm6mCKAP19xmF/QXc=,tag:gFj1g8BuhfJw8q1XO5tjgg==,type:str]
                TZ: ENC[AES256_GCM,data:vgpueLGy6iWsEmE0lQ==,iv:chVF+8ozHvAzbX14G8fVMVR8lbHKdyXBbQs6dgzTbt0=,tag:Im0RiRtLsPELJuTlq1cSzA==,type:str]
            backupSchedule: 0 3 * * *
        firefly-iii:
            # -- Set to false to not deploy Firefly III
            enabled: true
        importer:
            # -- Set to false to not deploy the importer
            enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdm9VdTJFUW9SVWdRSUJv
            UVZTblFOdkNrNHlHbEIzbzRUOTVFM2hiOVJjCm03d2ovUi82emhGZVpjZWpNcEF4
            c1Y3cW50Y3dRVWxDUi9KVnErVGVnQUUKLS0tIEk3QkZZVGlqNFNQMjdaQTdqK09N
            UWVML2lDUnE2amkxYmxVNzRzbEEvWmcKMfsnzgKEsoTcl3DlDQQaNOYK/TepwqD2
            O87l6CezAvlmxleEYeIaVmb9N9LciuUbYUtsa3o61H6qosFsD5mOHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T22:39:20Z"
    mac: ENC[AES256_GCM,data:FcQD9dC1Str2E7lI/mICg4oD5osfct/kSj6TVZBX3C545Jwpo2jjCe3KhmHk2AdcHwgziMt/emf0943qcifgLnac33Aw+/TTWx7W6zB8quYvcnMcL28vFOqKr36P+jU0e4tFrj1N0eS1LRvxXIYhpEi274aTKr+V+yb5IhVIDO0=,iv:iyIKnEXunokDc17SlQPDWQP8e0r8fsgwPoRIUeFGFPA=,tag:18TZFdJDjXAqt7o2zsEeFQ==,type:str]
    pgp: []
    encrypted_regex: ^(configs)$
    version: 3.8.1
