apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@markaplay.net
    privateKeySecretRef:
      name: letsencrypt-production-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token