---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@markaplay.net
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: admin@markaplay.net
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: api-token
        selector:
          dnsZones:
            - "markaplay.net"
        recursiveNameservers:
          - 1.1.1.1:53
          - 1.0.0.1:53