apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:rTbjm6BDDrYOKqyEOoUIeh9AA3E86YDkQH8iSjs7aXhH9cAaPoVQmg==,iv:TfmpuMU98vW8pbA5eylv13XHqH3ibS/HCdtukZg2bFg=,tag:ZySMqlFK6lsNQt/VhVZc1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ayt4OEVsczBPZERrZ2ts
            K2RteWVaUlBVYm9ITHdXMTdHdFBwUXFBbERvCkhCR3Vadm9aN0VvNW1Hb0N5WUM1
            cVZHRlF4NWRUQWJqU0NKcURHdW5LOU0KLS0tIDQ5RFZOdDh4RXZQdjREd01BT1Bt
            NEhFYnF4QjN1czU5TVVCeVI4Smw0Y2cKHrJqOrL3zJfqcnEXVQIYC6EKnL97nYvk
            S6ivno0hG16gRpSToafuJypqJdiLYR+qeg4xO+4rfOEZeu02O8nzRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T00:32:31Z"
    mac: ENC[AES256_GCM,data:melfDJscLCcjY9NSh/6Nnija61i6v7adf3eAXiIYZ0vVRlUelYfQta25bFBIK+wAz/ydher0pwMF96FjmZlY7tA/Y65N4kwIKKpSsGI9qlZkSl1rOyeA9ZN8ss8S08VnzjAqb1VCPttBgHtCYTGkv4K3o/2lAU77AcSW1NzZq3c=,iv:+HNl/baocyqiBpvD0XQV6Rlljj1sbC6pO/u778i/AZQ=,tag:mD2LWeOtWeDuMsjKSZePtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
