apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: checkmk
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: checkmk
      sourceRef:
        kind: HelmRepository
        name: checkmk
        namespace: flux-system
      version: 1.1.0