apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:ahNnw7/Vo04KfDyMKhvU7pwispFrt/W5WEeXxrvVmBTuPg/TdtR2iA==,iv:D9itQSrizbxl6eexX6tIKSS3tW3eluRQCJR828lyBdA=,tag:mYDBTp66uE1gfErbSUz8QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ayt4OEVsczBPZERrZ2ts
            K2RteWVaUlBVYm9ITHdXMTdHdFBwUXFBbERvCkhCR3Vadm9aN0VvNW1Hb0N5WUM1
            cVZHRlF4NWRUQWJqU0NKcURHdW5LOU0KLS0tIDQ5RFZOdDh4RXZQdjREd01BT1Bt
            NEhFYnF4QjN1czU5TVVCeVI4Smw0Y2cKHrJqOrL3zJfqcnEXVQIYC6EKnL97nYvk
            S6ivno0hG16gRpSToafuJypqJdiLYR+qeg4xO+4rfOEZeu02O8nzRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T21:40:41Z"
    mac: ENC[AES256_GCM,data:76dZ442X3xUv99B4iF2+Pu8HI5mQYBpLGYRV6ndgDjBKCgWTAeIGFmibBmeWZbGPXx46SDidIOsSRBwcTavGPYAEf669bqlKmeOTNbLuvLDMRhbvMtUGzD6vb3jtoifNLUZdiFPqfRkoLeLPLsw/GSxe6KjDn/jrcI0Ew0mfvfU=,iv:Y4yJl0/nMwGF74/w7RdRhJazPrzLtR92rxGNvEM88sY=,tag:qBnxw4xJ8cE30aALMEeOLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
