---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone-cert
  namespace: droneci
spec:
  secretName: drone-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "ci.lab.markaplay.net"
  dnsNames:
  - "ci.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: drone-web
  namespace: droneci
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ci.lab.markaplay.net`)
      kind: Rule
      services:
      - name: drone
        port: 8080
  tls:
    secretName: drone-cert