---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "vaultkube.lab.markaplay.net"
  dnsNames:
  - "vaultkube.lab.markaplay.net"