apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: default
  source:
    chart: vault
    repoURL: https://markaplay.jfrog.io/artifactory/api/helm/Hashicorp
    targetRevision: 0.22.1
    helm:
      releaseName: vault
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault