---
apiVersion: v1
kind: Service
metadata:
  name: gitness-service
  namespace: git
spec:
  selector:
    app: gitness
  ports:
  - name: http
    targetPort: 3000
    port: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitness-s-cert
  namespace: git
spec:
  secretName: gitness-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "git.lab.markaplay.net"
  dnsNames:
  - "git.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitness-ingress
  namespace: git
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`git.lab.markaplay.net`)
      kind: Rule
      services:
      - name: gitness-service
        port: 3000
  tls:
    secretName: gitness-cert