---
apiVersion: v1
kind: Service
metadata:
  name: gotify-service
  namespace: notifications
spec:
  selector:
    app: gotify
  ports:
  - name: http
    targetPort: 80
    port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gotify-s-cert
  namespace: notifications
spec:
  secretName: gotify-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "gotify.lab.markaplay.net"
  dnsNames:
  - "gotify.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gotify-ingress
  namespace: notifications
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gotify.lab.markaplay.net`)
      kind: Rule
      services:
      - name: gotify-service
        port: 80
  tls:
    secretName: gotify-cert