apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: gotify
  namespace: flux-system
spec:
  type: generic
  address: https://ntfy.ovh.markaplay.net/nasa-cluster-alerts
  secretRef:
    name: bearer-auth
