apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fossorial
  namespace: newt-system
spec:
  interval: 10m
  chart:
    spec:
      chart: fossorial
      sourceRef:
        kind: HelmRepository
        name: newt
        namespace: newt-system
      version: latest
    values:
      newInstances:
        - name: "main-tunnel"
          auth:
            existingSecretName: newt-key
