apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fossorial
  namespace: newt-system
spec:
  interval: 10m
  chart:
    spec:
      chart: newt
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: newt-system
      version: ">=1.0.0"
  values:
    newInstances:
      - name: "main-tunnel"
        auth:
          existingSecretName: newt-key
