apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  namespace: test
  annotations:
    metallb.universe.tf/address-pool: internal-pool
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer