---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
spec:
  selector:
    app: n8n
  ports:
  - name: http
    targetPort: 5678
    port: 5678
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-s-cert
  namespace: n8n
spec:
  secretName: n8n-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "n8n.lab.markaplay.net"
  dnsNames:
  - "n8n.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress
  namespace: n8n
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.lab.markaplay.net`)
      kind: Rule
      services:
      - name: n8n-service
        port: 5678
  tls:
    secretName: n8n-cert