---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    app: n8n
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-volv-pvc
  namespace: n8n
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deploy
  namespace: n8n
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - image: docker.n8n.io/n8nio/n8n:latest
        name: n8n-pod
        imagePullPolicy: Always
        ports:
          - containerPort: 5678
            name: http
        volumeMounts:
          - name: data-volume
            mountPath: /home/node/.n8n
        resources:
            limits:
              memory: 512M
            requests:
              memory: 512Gi
              cpu: "0.5"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: n8n-volv-pvc