---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: checkmk-tls
  namespace: monitoring
spec:
  secretName: checkmk-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "checkmk.lab.markaplay.net"
  dnsNames:
  - "checkmk.lab.markaplay.net"