---
apiVersion: v1
kind: Service
metadata:
  name: vsshcode-service
spec:
  selector:
    app: vsshcode-server
  ports:
  - name: ssh
    protocol: TCP
    targetPort: 22
    port: 22
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.49
