apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nasa-infra
  namespace: flux-system
spec:
  interval: 3m
  path: ./apps/overlays/nasa/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
