apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 1m
    chart:
        spec:
            chart: homepage
            sourceRef:
                kind: HelmRepository
                name: homepage
                namespace: flux-system
            version: 1.2.0
    values:
        config:
            bookmarks:
                - Developer:
                    - Github:
                        - abbr: GH
                          href: https://github.com/
            services:
                - truenas:
                    icon: https://styles.redditmedia.com/t5_zna4k/styles/communityIcon_anszrp6vc8w71.png
                    href: https://tn02.lab.markaplay.net
                    description: truenas scale server
                    widget:
                        type: truenas
                        url: ENC[AES256_GCM,data:22jPsq3tcQf72dVtdA/2+Nhkc0WKGbNqOFp96U0=,iv:3awZ2ItGVl1EgeFTnTvSjfEcAlNn0Yi/5AfXOb3mIXk=,tag:WQ4i4eX1SxZKXRl7s6x2lw==,type:str]
                        key: ENC[AES256_GCM,data:RdmDmlshsFddvQ6VmDdi0mTglAh85Osuw294DUEXgH3y2iy+Mv/+AHdRhpnbQ+7Ro3RI91Q9GL5q8xACcDJNjzjJ,iv:0QxALItpzXXkRqmPNzUPJF5wIKSRmmWLtdOqZWVUUss=,tag:Y11cevSvYBMmEn/+Krk1dg==,type:str]
                - proxmox:
                    icon: https://www.weehooey.com/wp-content/uploads/2018/11/Proxmox-logo-stacked-840px.png
                    href: https://epyc.lab.markaplay.net:8006
                    description: proxmox cluster
                    widget:
                        type: proxmox
                        url: ENC[AES256_GCM,data:Fgm74NRP03mkHo9MvPD+Anw0wY9qqWoOSOi+qOKseZYy9qE=,iv:qFUwX43UYvxn4Al6uSNfVWYtsROpoK9hpswRHJUeyr8=,tag:aRjOXOA1Ys3nMkHNjMrX4Q==,type:str]
                        username: ENC[AES256_GCM,data:NMb69iNLd2g/xooBNR0IqXH9Q6WPjXo=,iv:b9toHDQzrG6NCdwJT2imrse3wO3k0eS8o8N4EtpdNz4=,tag:8ATF01aBtqeJDmWpUqEKXA==,type:str]
                        password: ENC[AES256_GCM,data:MWr7hRL1VKbmZQ6Wg6epJrK9t8Yn3u3qh2nHY4PJ6BHjyQNz,iv:cdYmOi3ez9WFUqR8gZh2JN7SuTmmIjTLvTKXPX6DpB4=,tag:UVR5O+dBLyO8Lb/ce8tuBw==,type:str]
                - cloudflare:
                    icon: https://logos-marques.com/wp-content/uploads/2021/03/Cloudflare-Logo.png
                    href: https://dash.cloudflare.com/
                    description: cloudflare dashboard
                    widget:
                        type: cloudflared
                        accountid: ENC[AES256_GCM,data:d2Gj6Jtk6Zls7FofKTvYZ96vyPnrSiQJuV/EiSnE/bE=,iv:E+49haWB7WauVB0qaqTQ+H/Z1RwtSqS5t4jxHaDiloI=,tag:4bQoDtETxhHI1pyKCTjIrw==,type:str]
                        tunnelid: ENC[AES256_GCM,data:p99ND+uZZtcdPyMR64eDuDOKCl97X9bvplMIAML1fb91qYTM,iv:XzY9y8XqmQsLhbPyELrdgJHRTJS5wbJclve1GEWP0LM=,tag:Um325HqerarbnosC2FtIXw==,type:str]
                        key: ENC[AES256_GCM,data:nnYi/QWyMLiJ6ZNBEsxU4Q5ocoyE5fAbm1vld5jf5aglPTdwAS4IdQ==,iv:a24co8bKuu87fogsaUTlyaljwqaUYglY5ahurlJVtjg=,tag:qHzGF0E5/n/zhRuckvprPg==,type:str]
                - nextcloud:
                    icon: https://docs.ftscloud.ch/bookstack/uploads/images/gallery/2019-05-May/scaled-840-0/Nextcloud-logo-round.png
                    href: https://nextcloud.lab.markaplay.net
                    description: nextcloud server
                    widget:
                        type: nextcloud
                        url: ENC[AES256_GCM,data:/wzFSyyReVzL+Lp412F7rKFIfKNP2qV2X457bh4J0rGa09A=,iv:Ncfu6dKWU2UzRyd28Cchq+To3TsHgCudXpkcxAHvPKA=,tag:VkdTKhxcW5tBbAh9IH4Rdw==,type:str]
                        username: ENC[AES256_GCM,data:lkqvCgo=,iv:SNyIrZL60596mubVH8sRk5Qyc+yrxXnzUKn3DewtRsY=,tag:rl+2aVjff+Oc1751YhtJ8A==,type:str]
                        password: ENC[AES256_GCM,data:hHMPv9tXzdLr1NHJay3VkVAFrbT5b+TswRhm4qs=,iv:YHrq72qI5s0JvUvs/Xf+K3XvvKvMptkKyAhvpRiIABw=,tag:cCatBY//eOYcw70pNEK/+A==,type:str]
                - traefik:
                    icon: https://mwunderling.com/images/traefik_2/traefikproxy-vertical-logo-color.png
                    href: https://traefik.lab.markaplay.net
                    description: traefik kubernetes instance proxy
                    widget:
                        type: traefik
                        url: ENC[AES256_GCM,data:WsWxCV34axlmD5j0FbBCbS5nh6jGZnBBMVz3bFt1JD9o,iv:uJp8W67zuKcxwaGXoWoqsoTJynSOhtQRGTTo9EWFdl8=,tag:+ga4LeWTWYxISL8nk19ziw==,type:str]
                        username: ENC[AES256_GCM,data:BdvyVcE=,iv:ziMRJcbZkczuiBUp62yrFiDg53cG6lAbvVcpxFqcGEc=,tag:aI8aDc+p2QiUiBrvByHYBA==,type:str]
                        password: ENC[AES256_GCM,data:bZwHSOLuObPL6l9ZDA==,iv:gFz7H4s0V1M7HX4tvMPVr8gSLHg+SmV5w5+8tmfjSHI=,tag:APp+YCWwRgc2n8yNFoByRw==,type:str]
                - traefik-miniomega:
                    icon: https://mwunderling.com/images/traefik_2/traefikproxy-vertical-logo-color.png
                    href: https://traefik.miniomega.lab.markaplay.net:8080
                    description: traefik kubernetes instance proxy
                    widget:
                        type: traefik
                        url: ENC[AES256_GCM,data:8VaGLJxhrJIfzpuzgdVp9O+kdpiUaiWC9TSEaqs840AVVv7q8UFEecgaGGInf1iF,iv:aLqRRbrjmACA1yU/qKaDuMswu8AYfSDDhCBovhxG60U=,tag:Y23f/b9Sc+G4YYJlg7BTuA==,type:str]
                        username: ENC[AES256_GCM,data:zjn1kWo=,iv:zvlp2Qn/EXuZgfsuK67RB+oBRh92GdQGn5stwiNff9w=,tag:JMhqZ2t3XX0thtO2fqlHMw==,type:str]
                        password: ENC[AES256_GCM,data:4EuZ2eUOD/+TjuY/lw==,iv:kNfedIXXarCUc0JSIg/R30etXzLKTqn3CQleROEBsU0=,tag:FWi4nA/lZffEfg4SMyLjqA==,type:str]
                - grafana:
                    icon: https://1.bp.blogspot.com/-edrJnM1O7d4/XuuKLB9QkRI/AAAAAAAADbo/WMxBIK_fePAeVRq-EhA4_zslToI4i6veQCK4BGAsYHg/s1224/1200px-Grafana_logo.svg.png
                    href: https://mon.miniomega.lab.markaplay.net:3000
                    description: grafana stats dashboard thingy
                    widget:
                        type: grafana
                        url: ENC[AES256_GCM,data:d+4HjnlEpH0XqAQTsbbkAR8yjCydm/DkEaFq8xgtfJJDbTa4V2KQlKwjm2w=,iv:WW/U7LYRz6VZhZ6op0Ol0ZbIqya42CTBkzUFasaIo0Y=,tag:BPUHiiR7/vipzwNJucapZg==,type:str]
                        username: ENC[AES256_GCM,data:B93N0wG6+S1voPM=,iv:xszL3lzM0AdvKVEfrtiP4F3uK+WmwFU/nh+bW5cAmYw=,tag:bibxuZYznKK4rwfYjdxsDw==,type:str]
                        password: ENC[AES256_GCM,data:fQ/PHaoNQ+oMKCUqmYYFK2Bl/HJRfOdYy2+XiYYfGES2AeUfY4SXGyzmbaKJWA==,iv:LvpakWSX3YngNfGoqGG88ZLRJrlG6zB8Ckm4kQ95HgA=,tag:xu0e/VAgP0oaTaB7QcvEJA==,type:str]
                - proxmox-backup:
                    icon: https://www.weehooey.com/wp-content/uploads/2018/11/Proxmox-logo-stacked-840px.png
                    href: https://charlie.lab.markaplay.net:8007
                    description: proxmox backup server
                    widget:
                        type: proxmoxbackupserver
                        url: ENC[AES256_GCM,data:BwGg1TvJnNajSFrSkPiPynEs03XjzKoXljbA44U62v3zlx2A3Kw=,iv:WO52E7Eeb0zen0I+TIxO2fiupd17WZWekX58gRh2zes=,tag:EiJO2A4gx7MpszdfVo5JCA==,type:str]
                        username: ENC[AES256_GCM,data:bgFh3FaMmqbXCDc8UjJ4aDryJp58ZDJ3vus=,iv:0xK5h5kC5JfhreU+GbMNGjm9p5dJwLsYJEAG8yRpBYY=,tag:lwz1ZMjQEMS3M5o8JdHzhw==,type:str]
                        password: ENC[AES256_GCM,data:fQw5WIkiqvzRV+6A3TkaotvgqwUAztNClgY2UhIYlGppu26C,iv:XnXjMxH5C2/Iyjo+X2wtXWXsHiu83HebmYyEQEDaHrU=,tag:Ti7sg6rlAoNzp4PR0yZnww==,type:str]
                - portainer:
                    icon: https://autoize.com/wp-content/uploads/2017/02/Portainer-logo.png
                    href: https://portainer.lab.markaplay.net
                    description: portainer container administration service
                    widget:
                        type: portainer
                        url: ENC[AES256_GCM,data:umxYenI/HlxQHu9nEW0K1/3vXNyvP6f/ZiChuzkP6YyRack=,iv:Yty8I5PH34XS3B1l+g+1TK5zKZ0r5iZiURbxGYCwZiI=,tag:M0NbiZhFya4RM9uZw+ihiw==,type:str]
                        env: 2
                        key: ENC[AES256_GCM,data:YAnIF3emQLEHWqSK1bddZAAzLVfWa2BzFUbRbgs7Ir5P9aTl4fj153pdHFWEmkFb,iv:TA9Yw90gCbseNh/9W24ESNjpmMmLroOtWezt5CBhN0w=,tag:PufUIPcRrdxDvLPuH3a43Q==,type:str]
                - unifi:
                    icon: https://www.laub-home.de/images/9/97/UniFi-Logo.png
                    href: https://192.168.1.3
                    description: unifi cloud instance
                    widget:
                        type: unifi
                        url: ENC[AES256_GCM,data:LbkskNu2g3h3ld/Y5w9cc8qTow==,iv:Th0x3bkL0FX68ZZPt6Vh21m4gD5HasNuzgkWXxZoiYU=,tag:wY5xtoLuXUcDNTaUy5eD9w==,type:str]
                        username: ENC[AES256_GCM,data:XdvLLGObeMt68x8s,iv:p6rYrH8t3cJNzLQGz4DRRGzkegZez67DiGOi0/mWjj0=,tag:sEsN/jXoVx7OJCs+7GX+Rg==,type:str]
                        password: ENC[AES256_GCM,data:LR+/zlsmxTdYk5WgKE2BYwDofbErWzPgOA==,iv:q9kLyKMJF2T2YdxncjqYhl0inB/xB/4oQWS/2qAAxNY=,tag:5ijCLHvqtyged9CdDfNaqw==,type:str]
            widgets:
                # show the kubernetes widget, with the cluster summary and individual nodes
                - kubernetes:
                    cluster:
                        show: true
                        cpu: true
                        memory: true
                        showLabel: true
                        label: cluster
                    nodes:
                        show: true
                        cpu: true
                        memory: true
                        showLabel: true
                - search:
                    provider: custom
                    url: ENC[AES256_GCM,data:q2+bTPhsvgSJ43zPI/kb6A0laobXjKq1cC4=,iv:rnEdtGxrCCwSdIyD/Hkx2iFrrdyYwKLJkQp7l0lKcts=,tag:wleCkRAjd4XrfE6GZBYc6w==,type:str]
                    target: _blank
            kubernetes:
                mode: cluster
            settings: null
        # The service account is necessary to allow discovery of other services
        serviceAccount:
            create: true
            name: homepage
        # This enables the service account to access the necessary resources
        enableRbac: true
        ingress:
            main:
                enabled: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU2sxZXFDWUcvR3N1dWZB
            NTJiQ3NFSkw3K0hwMEQvUmZha3g0SDcvUFFVCkIza1FFYVk1NCtHRzRHUlM5N0oz
            c1hkV1BJZGN2b1JvOENyTGxEK0tQNGcKLS0tIGJPZzNkaXRFRlR1b1FLcTUwNUVm
            NTRPdEtxZXl2ZWhObXFLRGhndW5QWUUKGaX2KBp2V71kpyXdbL+Inj4dCswHzjMT
            IaxyYJLmGg3uON5NHkhyuAV0e+2i42+rl4uKpdkMb3uLA3RV3M+tpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T00:14:47Z"
    mac: ENC[AES256_GCM,data:OnzkO0SW+HtaQq3IeMl/8yczTwvxEn+eRj2RIdixpPC4mD8g1t0DNr4Hhp7ML3NTl8JCzdgMqAANjNsmozPTT1HqpO9QnpbjpKo7g2lJr4Nj05EAFbMIGxqJ8c2q4be9Hy7Y+s498sdGmtczXQoCfk0gx1mY/E9u0l0oxZbolzU=,iv:fYT6z4uByfFJN+RXuOEauytPPkB+xpxasPc1znjVKsw=,tag:5XqEAXIRlJ2RR0dMafhegg==,type:str]
    pgp: []
    encrypted_regex: ^(key|username|password|accountid|tunnelid|url)$
    version: 3.7.3
