---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuma
spec:
  secretName: kuma-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "uptime.cloud.markaplay.net"
  dnsNames:
  - "uptime.cloud.markaplay.net"
  - "uptime.cloud.cloud.markaplay.net"