apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - image: louislam/uptime-kuma:1.18.5-debian
        name: uptime-kuma
        volumeMounts:
          - name: uptime-kuma-vol
            mountPath: /app/data
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            memory: 256Mi
      volumes:
        - name: uptime-kuma-vol
          persistentVolumeClaim:
            claimName: uptime-volv-pvc