apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 1m
    chart:
        spec:
            chart: homepage
            sourceRef:
                kind: HelmRepository
                name: homepage
                namespace: flux-system
            version: 1.2.0
    values:
        config:
            bookmarks:
                - Developer:
                    - Github:
                        - abbr: GH
                          href: https://github.com/
            services:
                - truenas: null
                  icon: https://styles.redditmedia.com/t5_zna4k/styles/communityIcon_anszrp6vc8w71.png
                  href: https://tn02.lab.markaplay.net
                  description: truenas scale server
                  widget:
                    type: truenas
                    url: ENC[AES256_GCM,data:9U+0W5XMAa3Dw9bi5QHqqeEWQcuVk1jfd7Qtbms=,iv:jmr5H7Q1gdo9xjXgY3h9fDwkaS3RLpFEJLtjrRr8OGQ=,tag:x6NUCqZEJtkrwoWTXb9ZyA==,type:str]
                    key: ENC[AES256_GCM,data:bS7v1KEo2Gc5TPGGV8ar9y44ymtWjzQbgbllrUHIFcfvW8oBVJPMXx2rBdOKPHj57NjEZBhw9WHAb5dxRVVuunQk,iv:V13sj2e40KwO7qXW7EnTix08GQ3vhJlipq/sV17si/Q=,tag:V6Q/VYXEV3Sovj05gMHjSA==,type:str]
                - proxmox: null
                  icon: https://www.weehooey.com/wp-content/uploads/2018/11/Proxmox-logo-stacked-840px.png
                  href: https://epyc.lab.markaplay.net:8006
                  description: proxmox cluster
                  widget:
                    type: proxmox
                    url: ENC[AES256_GCM,data:SnLHa1xWeqx+L2D8eUvXygW36q9FdI6htYqZpuEH/AqajVA=,iv:TbPEyHlWszI7I7x/iyOwfmw2gSKvo2e9eRdCAOBoQpM=,tag:8W7qUqRo1TI3sxIW7zlkQg==,type:str]
                    username: ENC[AES256_GCM,data:slX5pr1PTdCSDlmH6k5bF0rIEHbR0WE=,iv:M6fIhVTr1ktCV080628QTEoxXGkyXqeYutpy8u1CZy4=,tag:QMFnwYLYir0qI0uy2NdPZA==,type:str]
                    password: ENC[AES256_GCM,data:qKC1y59m25njnV8MCbnbIq1TkqlyuiKbZwkqIWgR5FAfPNJa,iv:E+hhrbzBKMbHFLCGsdgc9Bq0T7tWNdWwga8nBjFUvOQ=,tag:x9qlscLxXxi/pFYwfL2m9A==,type:str]
                - cloudflare: null
                  icon: https://logos-marques.com/wp-content/uploads/2021/03/Cloudflare-Logo.png
                  href: https://dash.cloudflare.com/
                  description: cloudflare dashboard
                  widget:
                    type: cloudflared
                    accountid: ENC[AES256_GCM,data:Tb4oY6ZRbDBpIEvANeLl7iaMMgIg6Wb2qRIak97PasA=,iv:Tte6TaX0diaWXvG9QhCS/3ur+6k55iGpkm5ZFiqxHtY=,tag:DWAmcvDTOl0zDAygiVZu8Q==,type:str]
                    tunnelid: ENC[AES256_GCM,data:pMw5f8srGeHCyi20xhmg5FQLX2hKwYv1KGWrKDViT/YH8IfB,iv:7S0wh2alaYXTrmNoUp59/3an3GO36AK+PPuzErLWBdM=,tag:CrbLWTUj5wcWgVn6A8UkBQ==,type:str]
                    key: ENC[AES256_GCM,data:ggVyQHjA1TWXsrKocm3BSRzaZcSZGZYfmRuADPsz+j8ASJEzliqrWg==,iv:OzwXy6Vy6Pd1CbIehZ4jJXqKK2h91fHRZz/ZrI/7tGc=,tag:r8iJwCTf+I1X0SJffQBiKQ==,type:str]
                - nextcloud: null
                  icon: https://docs.ftscloud.ch/bookstack/uploads/images/gallery/2019-05-May/scaled-840-0/Nextcloud-logo-round.png
                  href: https://nextcloud.lab.markaplay.net
                  description: nextcloud server
                  widget:
                    type: nextcloud
                    url: ENC[AES256_GCM,data:ywNSwYLP7gPd9djCxurBN/FsrNB0l5Q2MmJaD2AvXZd1nS0=,iv:DpGxfdeaVjBRjPYs6zXkZAxCCBwZMUi9bg+0hxLW0UI=,tag:/lJLTZaA4croYhzGPOIPaQ==,type:str]
                    username: ENC[AES256_GCM,data:miQUDc4=,iv:UPzkJkEvuK/h9st8jEGKvVAZA6FreJCwsMKgBd0klXs=,tag:EIjnW9/xYtZOq190okNpdg==,type:str]
                    password: ENC[AES256_GCM,data:7GuftC5FhK/Kk0ICFkUfWZUsmnodvOCH4zGEpAU=,iv:gBkhLE9x44YzqNA8A99DFeWmNGvqcztuFFjnAqZBkGs=,tag:povbOfXfu+e43mXmtl/T8Q==,type:str]
                - traefik: null
                  icon: https://mwunderling.com/images/traefik_2/traefikproxy-vertical-logo-color.png
                  href: https://traefik.lab.markaplay.net
                  description: traefik kubernetes instance proxy
                  widget:
                    type: traefik
                    url: ENC[AES256_GCM,data:1DB3buPid+Ws+WltD+hEk7s0PhAVl/rRdZQqqHrQ8w3W,iv:jf49gR9jO5ezR9uiVXxjgXbYxMzx7abtEyANe/3iFSE=,tag:rFTAnveqWB3xuzusnu+HkQ==,type:str]
                    username: ENC[AES256_GCM,data:Oy9wXZU=,iv:uDkdxVEPbJRcKBq1sTHtZfXGOcwmeU15DJr/NAkpBRg=,tag:sDEadbvrVR7s2JGkRy72ag==,type:str]
                    password: ENC[AES256_GCM,data:7qdG0v54siPdagvZXw==,iv:8Dm3U0IXtzUu8EXI5chCgHWmTgevG4S6tjYVsXP5iJI=,tag:CYZY3cjOE8z3q9PQzsYoew==,type:str]
                - traefik-miniomega: null
                  icon: https://mwunderling.com/images/traefik_2/traefikproxy-vertical-logo-color.png
                  href: https://traefik.miniomega.lab.markaplay.net:8080
                  description: traefik kubernetes instance proxy
                  widget:
                    type: traefik
                    url: ENC[AES256_GCM,data:kmAbFmWiMPqBwwwV4u2o+/D4gRNPb2YRniC4z4S9Int6ZbFQlDrQZ3VT7wAcPHoC,iv:jUj2SVN+C7PremhvCtWlh0zj3bqF8Emzir1pwRdhS1w=,tag:KKXUng7GPQfCN5ylXHFyPA==,type:str]
                    username: ENC[AES256_GCM,data:NInsPII=,iv:4XSS4DI1ck+nD1XUHcv1OiaLMm2ja7od/ebDTp4ShB8=,tag:yCrEsh6nnSAX8CON7iCmGw==,type:str]
                    password: ENC[AES256_GCM,data:2IvTo4xVdkxoKucayQ==,iv:zqQDrwZFE4xj1cKUiBbWce2JlH6hCspesPhA/1AAOaA=,tag:zMMnWHIQ9uI2BPENX/wDpA==,type:str]
                - grafana: null
                  icon: https://1.bp.blogspot.com/-edrJnM1O7d4/XuuKLB9QkRI/AAAAAAAADbo/WMxBIK_fePAeVRq-EhA4_zslToI4i6veQCK4BGAsYHg/s1224/1200px-Grafana_logo.svg.png
                  href: https://mon.miniomega.lab.markaplay.net:3000
                  description: grafana stats dashboard thingy
                  widget:
                    type: grafana
                    url: ENC[AES256_GCM,data:rLUaeTry+0qLkaQLNnfyQma581AxVYCL6iTegifdQkzObgEvSe/bBiThmwM=,iv:B4JiTfeJW0PmNrpLNFyD+tm6eo4Yv5rkShBuO8sPOQM=,tag:B80GNMUmnqgVX4izecL4zw==,type:str]
                    username: ENC[AES256_GCM,data:7hwk7+dLFaf9PTQ=,iv:zZAJbwIsmYePmdJZj9K/WRknw4zUTUYCQsjqq/tXG2g=,tag:vPDfz9qrxqe6Zql4IIRFHw==,type:str]
                    password: ENC[AES256_GCM,data:0JNBbTfgm++jt3L1DM8/dqy3JeGQhxra+OmS4tUEu8LYhL1kHCL3AGX4rbQpww==,iv:IJDMjkxx6kpfQEryhuNaljJ2QZe521vROsBmnE30pzg=,tag:K6iLOc6ZrLsAhFVXY0V0Sg==,type:str]
                - proxmox-backup: null
                  icon: https://www.weehooey.com/wp-content/uploads/2018/11/Proxmox-logo-stacked-840px.png
                  href: https://charlie.lab.markaplay.net:8007
                  description: proxmox backup server
                  widget:
                    type: proxmoxbackupserver
                    url: ENC[AES256_GCM,data:9J89hGzxphxNVu/z9KP19ihhhSbtdhfwJ8kXjV7jQQyoUF5Dx3o=,iv:bIAmsFiRSQQ5phYtGfrnki9Jep9WnzQQ3PeTYOlcws8=,tag:yDR70EKgG8XayYeTaPRbPA==,type:str]
                    username: ENC[AES256_GCM,data:F9aBU/n+UbtQx/CAyXHO8Ix/XXB6kN/FhZs=,iv:AEAxcPBNJ7ap1y22Ac3n9szrwQ3wR6fFRkReUK975Z8=,tag:fgqMjfywZXykp9vs03SV3g==,type:str]
                    password: ENC[AES256_GCM,data:0LaaJL0margIWymZn+TUDEJ+h77ycnQ8qm17rAyZuxoNCv2T,iv:fQosw1LNznZt/o9Ft5kQM3YHlN0fZKtqUoYqRDE+BQE=,tag:lCm/6D+ZBbw6d1AYTZ9heg==,type:str]
                - portainer: null
                  icon: https://autoize.com/wp-content/uploads/2017/02/Portainer-logo.png
                  href: https://portainer.lab.markaplay.net
                  description: portainer container administration service
                  widget:
                    type: portainer
                    url: ENC[AES256_GCM,data:Tnct/G9FbI3Nb26Zy6viG3N3/YAC3s2P3fq/XuYLEImKsZs=,iv:MIyTtb7FmgtHB4WY4xhiBJrQzSuALbZY9l4rUlwdvs0=,tag:YDBfW81hFZxx7kqprokKDg==,type:str]
                    env: 2
                    key: ENC[AES256_GCM,data:zFvlRavx2cCJcGGGyqSKwQd/ipQ0CmeMfgZV4dDEIzRloNRu7ZBDNE7Cd4BaCutq,iv:uSNk3HbFFPT/uqhTLGskRK14Ge9C1h/bZJdXTw3RgUg=,tag:FKmxlEp5tEwrFZt2bt4jyA==,type:str]
                - unifi: null
                  icon: https://www.laub-home.de/images/9/97/UniFi-Logo.png
                  href: https://192.168.1.3
                  description: unifi cloud instance
                  widget:
                    type: unifi
                    url: ENC[AES256_GCM,data:Zd811RGU+xWWTNn/y4/2m4tfVQ==,iv:JdJrtLBMhuH9SwR0eKjXT1v2fM0rrZHqC09tmpARvL4=,tag:LyHGYRJlmqe35WWXaOgeQg==,type:str]
                    username: ENC[AES256_GCM,data:jCQrggp/l8iGl5wo,iv:41Aa70h+W7aB5oam1zAKjQSGW3Z6KZ8pEVyaw+rEcZE=,tag:ssra4EuD+6NCXWwyIBAXKQ==,type:str]
                    password: ENC[AES256_GCM,data:XEwirBY9UdQTn/PqgNMkLk4Rkq8r+qsYDA==,iv:ke2DF800BOjVdi4bfp4rgaew+1q2p4fo7ptQjtIA810=,tag:YN8mVO6vaCTefvjWQUMf/g==,type:str]
            widgets:
                # show the kubernetes widget, with the cluster summary and individual nodes
                - kubernetes:
                    cluster:
                        show: true
                        cpu: true
                        memory: true
                        showLabel: true
                        label: cluster
                    nodes:
                        show: true
                        cpu: true
                        memory: true
                        showLabel: true
                - search:
                    provider: custom
                    url: ENC[AES256_GCM,data:q2+bTPhsvgSJ43zPI/kb6A0laobXjKq1cC4=,iv:rnEdtGxrCCwSdIyD/Hkx2iFrrdyYwKLJkQp7l0lKcts=,tag:wleCkRAjd4XrfE6GZBYc6w==,type:str]
                    target: _blank
            kubernetes:
                mode: cluster
            settings: null
        # The service account is necessary to allow discovery of other services
        serviceAccount:
            create: true
            name: homepage
        # This enables the service account to access the necessary resources
        enableRbac: true
        ingress:
            main:
                enabled: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU2sxZXFDWUcvR3N1dWZB
            NTJiQ3NFSkw3K0hwMEQvUmZha3g0SDcvUFFVCkIza1FFYVk1NCtHRzRHUlM5N0oz
            c1hkV1BJZGN2b1JvOENyTGxEK0tQNGcKLS0tIGJPZzNkaXRFRlR1b1FLcTUwNUVm
            NTRPdEtxZXl2ZWhObXFLRGhndW5QWUUKGaX2KBp2V71kpyXdbL+Inj4dCswHzjMT
            IaxyYJLmGg3uON5NHkhyuAV0e+2i42+rl4uKpdkMb3uLA3RV3M+tpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T00:11:10Z"
    mac: ENC[AES256_GCM,data:qx3hOYIq0ReRre83VMuVh1adzQk5tDqNpIgEJWl1Y4rJvkSEVPP044Ms5f38+8shlYKTR+rLRcJ0OLx80CSDA2BgGXLsK+Llll4xUFvysHRbmM+8DR+f9DuY4PZ4oKsthxmAwiHzHvYhgkpOdDJxEmqbU0Y33KT+Bsya0RTiCaQ=,iv:iW9x+s/ZzrqHud4j2vKtcat+YeD66WlfTVDv2UJUKcM=,tag:Z2Z1P6HLzXKjsdDMfx2vsw==,type:str]
    pgp: []
    encrypted_regex: ^(key|username|password|accountid|tunnelid|url)$
    version: 3.7.3
