---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "longhorn.lab.markaplay.net"
  dnsNames:
  - "longhorn.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.lab.markaplay.net`)
      kind: Rule
      services:
      - name: longhorn-frontend
        port: 80
  tls:
    secretName: longhorn-tls
