apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
type: Opaque
stringData:
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:ayAgNBnSNq4ED1BIbt6DXpc=,iv:IQw0vhI0Pr7boD7AM0mpXI14tHOOMdLc2T0ZuNfBJMQ=,tag:QYcn37Qv4UIAdPSE2ZJ9zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fv794lyehmnq5urum5sauj04ukdkec6vk0p36dpmf07kczkvapswrpvs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZjNBb0Y4djdaWVo4cWln
            MFdxSWJIcTFwMUI4bmtnMTh2MXRreVkrV1RZCktzT1AxSVlscGFBdmV2cko5aHVG
            UjN1ekVIZHhLcHd4dU1NbDBjY1hlS1kKLS0tIDRUM3dzaEpJM2ZPdElDeVQ2cW9p
            ZjRFOHpyWFBlQ0xodDU3YW5KKzZuY28KLppE3x3TMuN38Po0QuAQEwA81sxG68ih
            jwLxy8S/iNTRf9VQ6CDZ0Bp3evI/62l0N3lb3/B7FtDUYyyP47dQjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T00:15:20Z"
    mac: ENC[AES256_GCM,data:PrfAnKdmyX3MwFDUafYiw7y4+vdCUMa8wPHoAPwhwam8vixnu2CFTcPYNB8vN4XJMiwwt6YzHBGSbSqPk3QAyVmsofW0cJ9AWmB6IT33zPod5Z7FGf13ujwiGwRclnG6n15GmXuFo1fj3rYjDkSO5ywE1OJKbwiL3A3vafHGTLA=,iv:qW95YGdlLeRQOF9upY+1YMm2ai6BOBFg7Vd5VldA7xg=,tag:uNS/GLbQadYRc5eIX0mUUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
