apiVersion: v1
kind: PersistentVolume
metadata:
  name: dns-volv-pv
  namespace: dns
  labels:
    type: rook-ceph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-volv-pvc
spec:
  storageClassName: rook-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
