apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs