---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntfy-cert
spec:
  secretName: ntfy-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "ntfy.lab.markaplay.net"
  dnsNames:
  - "ntfy.lab.markaplay.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy-web
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ntfy.lab.markaplay.net`)
      kind: Rule
      services:
      - name: http-ntfy-out
        port: 80
  tls:
    secretName: ntfy-cert