apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../../../base/traefik
  - default-headers.yaml
  - middleware.yaml
  - ingress.yaml
  - secret-dashboard.yaml
  - traefik-cert.yaml

configMapGenerator:
  - name: traefik-overlay-values
    behavior: create
    namespace: traefik
    files:
      - values.yaml=values-huston.yaml
generatorOptions:
  disableNameSuffixHash: false

# Let kustomize rewrite the name hash inside HelmRelease.spec.valuesFrom
configurations:
  - kustomizeconfig.yaml
