---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik
spec:
  secretName: traefik-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "traefik.lab.markaplay.net"
  dnsNames:
  - "traefik.lab.markaplay.net"
