apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: monitoring
      version: 82.10.x
  values:
    prometheus:
      prometheusSpec:
        externalLabels:
          cluster: "huston"
    alertmanager:
      enabled: false
    grafana:
      enabled: false
