apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord
type: Opaque
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:zSXYboDKwl6GHXDrXPBTUM2beQfimKiCPb793e/sfuqxuw/1hP56uFWoria14GFjnoNwYtDJczkHpSKdk6Uyc87ZUCPUEg==,iv:NiZYYNgnjk8cvCPy/kMFUEX6Bc4JjB6vPZytaIuuU9Q=,tag:diik3NfamkQpjCHiYZtnMQ==,type:str]
    BOT_PREFIX: ENC[AES256_GCM,data:OQ==,iv:2dor6SGO2Ke6rWn/YlycalAgwLsD8fQPzU8komHvIuc=,tag:4tEO2Uh3npirLkkCpJGsVw==,type:str]
    API_URL: ENC[AES256_GCM,data:f+jCdiYO8aq64JgUv6UFwfjj5g1OAK/vte6gDNbjZtta9TPwtnJcWbAi9WC+IINLt+Mo0lv4P/EQjAAlfivWaMYYWagddOdbDuRTNodLDL2xFE0byEtKLfiLPuDCKjQaq8A4U9Bez6P+pk4=,iv:9lmiDFxtzE2HCu3zzDSfAp1QoJ3Stt/DXEQNAjH1aXA=,tag:PgdiBbxI+qyacWeGt5iiJw==,type:str]
sops:
    age:
        - recipient: age1z009ewmj2adfms328f3mc6aux27qq4d2mwhyunat9ul5x9k3fydq8mzxhr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ykdtb1dUVC9qU29yU1k2
            M3paMjFNcE81YlA3RkNmRm1yKytGdGZDU0RNCjJzem8zOGJMa25zZXNNZVlTd1ZZ
            NkFMdzVSbG5BM2tyL2pUblcvS0VMSjQKLS0tIGZaamVYVzhtYWwrMmhBd3hOU2xv
            YzRRRFpGVEo0eXRQM3d0L2VPRTJWUUkKHgytdiw5o+N/tezLpmnL9OcD4pK9GM14
            uYUgYNJ+QI6PMIP8k46Zfn4HNEPZqqrcXmy/q/+HonzR/hD90YdrRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T23:24:54Z"
    mac: ENC[AES256_GCM,data:kXJhsgqUVfD224taOw27PLpH0wz1hIc42eTx4AmevWEiUnvgIxmhakZk3Gk5UzNANJETVX4C3iGHLOr6FWgM7SbASz5tE5pYWNq3/gjXMVtoNuJN7psMdUSDAh6NQFjxYGoHS2J39Y91AcIqNsYjm0E8x5EIBmFAm48Abmv/NU4=,iv:2hSEhSHaynn0LMappcgI9Zfa3/N1d5dBikRPUf8KLdc=,tag:lLuCQNq796uO5UFJTGTNbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
