---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 1m
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: 9.0.4
  values:
    gitlab:
      admin:
        existingSecret: gitlab-admin
    redis-cluster:
      enabled: true